Opaque token support for Reactive/WebFlux applications
okta/okta-spring-boot pull request #212
Opened 2020-11-05 14:06 UTC by sergiishamrai-okta

Opaque token support for Reactive/WebFlux applications

2020-11-05 14:57 UTC, bdemers commented on oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig.java
> +                    log.error(ex.getMessage(), ex);
fail here, throw an Illegal Arg or some other type of RuntimeException.

2020-11-05 14:59 UTC, bdemers commented on oauth2/src/test/groovy/com/okta/spring/boot/oauth/AutoConfigConditionalTest.groovy
> +            "okta.oauth2.client-id=test-client-id")
The existing tests _should_ function the same way to ensure backward compatibility with the previous version
NOTE: It is possible the tests make improper assumptions though, and will need to be updated

2020-11-05 15:00 UTC, bdemers commented on oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig.java
> +                        http.oauth2ResourceServer().opaqueToken();
Some type of converter must be used to similar to line 82 below

2020-11-05 15:06 UTC, bdemers requested changes
More tests needed,
We need tests that cover these new code branches

This code makes the assumption that setting a client Id and secret should trigger opaque config. This isn't correct.

The user's app _should_ determine this, either by calling `.jwt()` or `.opaqueToken()`.
If one of these methods have NOT been called by the user's app, then it should fallback to the following:

if `isRootOrgIssuer == true` -> opaque
else configure JWT

**NOTE:** opqaueToken configuration should ONLY be used in cases of `rootOrgIssuer` or the user's app explicitly calls `.opaqueToken()`

2020-11-05 18:51 UTC, arvindkrishnakumar-okta commented on oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig.java
> +                if (!isEmpty(oktaOAuth2Properties.getClientId()) && !isEmpty(oktaOAuth2Properties.getClientSecret())) {
This condition could mean we could do JWT as well. I don't think this is a qualifying/sufficient condition to start a Opaque token flow.l

2020-11-05 18:51 UTC, arvindkrishnakumar-okta requested changes
See my comment above. Also, need more tests to cover the new code paths.

2020-11-10 22:13 UTC, arvindkrishnakumar-okta commented on oauth2/src/main/java/com/okta/spring/boot/oauth/ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig.java
> +                if (!isEmpty(oktaOAuth2Properties.getClientId()) && !isEmpty(oktaOAuth2Properties.getClientSecret())) {
@sergiishamrai-okta check this out: https://github.com/okta/okta-spring-boot/pull/213/files

2021-09-13 19:51 UTC, mraible commented
@sergiishamrai-okta Please rebase to fix conflicting files.

2023-08-22 11:54 UTC, closed without merging